site_name: Bright
site_description: >-
  A scriptable tool for transforming and transpiling Luau code.
site_url: https://brightluau.dev/

repo_name: brightluau/bright
repo_url: https://github.com/brightluau/bright

edit_uri: edit/master/docs/

theme:
  name: material
  custom_dir: docs/overrides/

  logo: assets/images/logo.svg
  favicon: assets/images/favicon.svg

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.instant.preview

    - navigation.indexes

    - navigation.tabs

    - navigation.path

    - navigation.top

    - navigation.footer

    - search.suggest
    - search.highlight
    - search.share

    - announce.dismiss

    - content.tooltips

    - content.action.edit
    - content.action.view

    - content.code.copy
    - content.code.annotate
    - content.code.select

    - content.footnote.tooltips

  icon:
    repo: fontawesome/brands/github
    tag:
      yields: material/clock
      experimental: material/flask
      unstable: material/fire-alert
      internal: material/eye-off

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - name: GitHub
      icon: fontawesome/brands/github
      link: https://github.com/brightluau

  consent:
    title: Freshly baked cookies, anyone?
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well as to measure the effectiveness of our
      documentation and whether users find what they're searching for. With your consent, you're helping us to make our
      documentation better. If they're not your cup of tea though, you don't need them to read (that'd be absurd)!
    actions:
      - accept
      - reject
      - manage

  tags:
    Yields: yields
    Experimental: experimental
    Internal: internal

copyright: >-
  <a href="#__consent">Change cookie settings</a>

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html

  - toc:
      permalink: true

  - pymdownx.betterem
  - pymdownx.details

  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      anchor_linenums: true
  - pymdownx.inlinehilite

  - pymdownx.snippets:
      auto_append:
        - docs/includes/abbreviations.md
  - pymdownx.superfences

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - tags:
      tags_allowed:
        - Yields
        - Experimental
        - Internal

  - privacy:
      enabled: !ENV [CI, false] # disabled since external assets should only be downloaded at buildtime

  - git-revision-date-localized:
      enabled: !ENV [CI, false] # calculating git revisions on a local devbuild of the docs is useless
      enable_creation_date: true

  - git-committers:
      enabled: !ENV [CI, false] # same as above
      repository: brightluau/bright
      branch: master
      token: !ENV [GITHUB_TOKEN]

  - typeset
  - optimize
  - social:
      enabled: !ENV [CI, false] # only should be built in CI
      debug: false # doesn't apply to builds, only in testing

      cards_layout_dir: docs/layouts/
      cards_layout: social_card

hooks:
  - docs/overrides/hooks/shortcodes.py

exclude_docs: |
  includes/

nav:
  - Home: index.md
  - Get Started:
    - get-started/index.md
    - badges.md
    - changelog.md
  - User Guide:
    - user-guide/initializing-a-project.md
  - Transformers:
    - transformers/index.md
    - transformers/community.md
  - Developer Guide:
    - developer-guide/index.md
    - Poke:
      - developer-guide/poke/index.md
      - developer-guide/poke/why.md
    - Transformonomicon:
      - developer-guide/transformonomicon/index.md
      - Tutorials:
          - developer-guide/tutorials/transformer-basics.md
      - developer-guide/transformonomicon/configuration.md
    - Bright:
      - developer-guide/bright/index.md
  - API:
      - api/index.md
      - Standard Library:
          - api/std/Config.md
          - api/std/registerTransformer.md
          - api/std/_getTransformers.md
