name: Test

on:
  push:
    branches:
      - master
    paths:
      - src/**/*
      - tests/**/*
      - include/**/*
      - pesde.toml
      - pesde.lock
      - .github/workflows/test.yml

  pull_request:
  workflow_dispatch:
  merge_group:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Setup pesde
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download -R pesde-pkg/pesde -p "*-linux-x86_64.zip"

          mv pesde*.zip pesde.zip
          unzip pesde.zip
          chmod +x pesde

          ./pesde self-install

          echo -e "$HOME/.pesde/bin\n$PWD" >> $GITHUB_PATH

          rm pesde

      - name: Install project
        run: pesde install

      - name: Run Tests
        run: lune run tests

      - name: Lint
        run: selene --color always --allow-warnings src/

      - name: Style Check
        run: stylua --color always -c .
