name: Test

on:
  push:
    branches:
      - master
    paths:
      - src/**/*
      - tests/**/*
      - include/**/*
      - pesde.toml
      - pesde.lock
      - .github/workflows/test.yml

  pull_request:
  workflow_dispatch:
  merge_group:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Lint
        run: selene --color always --allow-warnings src/

      # regarding if: always(), these should always run regardless of previous failures

      - name: Style Check
        if: always()
        run: stylua --color always -c .

      - name: Run Tests
        if: always()
        run: lune run tests
